server:
  port: 5101

feign:
  httpclient:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-paycloud5101
    prefer-ip-address: true

spring:
  application:
    name: propertymanagement-paycloud-consumer



info:
  app.name: zifeng-propertymanagement
  company.name: www.scau.zifeng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$